Repository Kernel360/F1-WashFit-BE, pull requests merged in 2023-12, with the labels that each got.

#3 docs : add issue template
  .github/ISSUE_TEMPLATE/washpedia-이슈-템플릿.md
Labels: ⚙️ Setteings

#4 docs : add pull request template
  .github/pull_request_template.md
Labels: ⚙️ Setteings

#6 [feat] jasypt 암호화, flyway 초기 설정 구성
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/db/migration/V1.0.0__init.sql
  src/test/resources/application.yml
Labels: 💾 Database, ⚙️ Setteings

#13 코드 컨벤션 1차 진행사항 반영
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberRequest.java
  module-api/src/test/java/com/kernel360/ModuleApiApplicationTests.java
  module-domain/build.gradle
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/brand/entity/Brand.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
Labels: 🖥️ BackEnd, ⚙️ Setteings
