Repository Kernel360/F1-WashFit-BE, pull requests merged in 2024-01, with the labels that each got.

#14 Feat common code
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/commoncode/controller/CommonCodeController.java
  module-api/src/main/java/com/kernel360/commoncode/dto/CommonCodeDto.java
  module-api/src/main/java/com/kernel360/commoncode/service/CommonCodeService.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-api/src/test/java/com/kernel360/commoncode/service/CommonCodeServiceTest.java
  module-common/build.gradle
  module-common/src/main/java/com/kernel360/utils/ConvertSHA256.java
  module-common/src/main/java/com/kernel360/utils/JWT.java
  module-domain/src/main/java/com/kernel360/commoncode/entity/CommonCode.java
  module-domain/src/main/java/com/kernel360/commoncode/repository/CommonCodeRepository.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#17 Refactor common code :: 공통코드 도메인 리팩터링
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/commoncode/controller/CommonCodeController.java
  module-api/src/main/java/com/kernel360/commoncode/service/CommonCodeService.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-api/src/test/java/com/kernel360/commoncode/service/CommonCodeServiceTest.java
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/commoncode/entity/CommonCode.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#19 chore :: flyway SQL v.1.0.0 수정
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
Labels: 💾 Database, ⚙️ Settings

#23 feat: aop 로깅 및 logback 설정
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/aop/LogAspect.java
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/logback-spring.xml
Labels: 🖥️ BackEnd, 💡 Feature, ⚙️ Settings

#24 [feat] aop 로깅, logback → 코드리뷰 반영 수정
  module-api/src/main/java/com/kernel360/aop/LogAspect.java
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/logback-spring.xml
Labels: 🖥️ BackEnd, 🔨 Refactor

#27 회원가입 기본 로직 작성
  module-api/src/main/java/com/kernel360/commoncode/dto/CommonCodeDto.java
  module-api/src/main/java/com/kernel360/member/config/AuditConfig.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-common/build.gradle
  module-common/src/main/java/com/kernel360/utils/ConvertSHA256.java
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/config/JpaConfig.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
Labels: 🖥️ BackEnd, 💡 Feature

#29 [feat] flyway sql modify
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
  module-api/src/main/resources/db/migration/V1.0.1__alter_seq_increment.sql
  module-api/src/main/resources/db/migration/V1.0.2__insert_common_code_initial_data.sql
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#30 [feat] add JasyptEncryptor to module-common
  module-api/src/main/resources/application-local.yml
  module-common/build.gradle
  module-common/src/main/java/com/kernel360/utils/jasypt/EncryptionConfiguration.java
  module-common/src/main/java/com/kernel360/utils/jasypt/JasyptEncryptor.java
Labels: 🖥️ BackEnd, ⚙️ Settings

#32 Update cr.yml
  .github/workflows/cr.yml
Labels: ⚙️ Settings, 💬 Gpt Review

#35 회원가입 기본 로직 작성 (재업)
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-common/src/main/java/com/kernel360/utils/ConvertSHA256.java
  module-common/src/main/java/com/kernel360/utils/JWT.java
  module-domain/src/main/java/com/kernel360/auth/entity/Auth.java
  module-domain/src/main/java/com/kernel360/auth/repository/AuthRepository.java
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, 💡 Feature, 💬 Gpt Review

#37 Refactor login :: 로그인 리팩터링
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-common/src/main/java/com/kernel360/utils/ConvertSHA256.java
  module-common/src/main/java/com/kernel360/utils/JWT.java
  module-domain/src/main/java/com/kernel360/auth/entity/Auth.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, 🔨 Refactor, 💬 Gpt Review

#39 [feat] log filter 추가 및 aop 수정
  module-api/src/main/java/com/kernel360/aop/LogAspect.java
  module-api/src/main/java/com/kernel360/global/annotation/LogExecutionTime.java
  module-api/src/main/java/com/kernel360/global/aop/LogAspect.java
  module-api/src/main/java/com/kernel360/global/filter/LogFilter.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#40 [feat] 신고대상생활화학제품 정보를 가져오는 배치 작업
  module-api/src/main/resources/db/migration/V1.0.3__initialize_batch_job_schema.sql
  module-api/src/main/resources/db/migration/V1.0.4__create_reported_product_table.sql
  module-batch/build.gradle
  module-batch/gradlew
  module-batch/gradlew.bat
  module-batch/src/main/java/com/kernel360/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/java/com/kernel360/modulebatch/client/ReportedProductClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/client/ReportedProductDetailClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/dto/ReportedProductDetailDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/dto/ReportedProductDetailListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/dto/ReportedProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/dto/ReportedProductListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/job/ReportedProductApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/job/ReportedProductDetailItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/job/ReportedProductListItemReader.java
  module-batch/src/main/java/com/kernel360/modulebatch/job/ReportedProductListItemWriter.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ReportedProductScheduler.java
  module-batch/src/main/java/com/kernel360/modulebatch/service/ReportedProductService.java
  module-batch/src/main/resources/application-local.yml
  module-batch/src/main/resources/application.yml
  module-batch/src/main/resources/logback-spring.xml
  module-batch/src/test/java/com/kernel360/modulebatch/client/ReportedProductClientTest.java
  module-batch/src/test/java/com/kernel360/modulebatch/job/ReportedProductApiJobConfigTest.java
  module-batch/src/test/java/com/kernel360/modulebatch/service/ReportedProductServiceTest.java
  module-batch/src/test/resources/application.yml
  module-domain/src/main/java/com/kernel360/base/BaseRawEntity.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProduct.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProductDetails.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProductId.java
  module-domain/src/main/java/com/kernel360/ecolife/repository/ReportedProductRepository.java
  settings.gradle
Labels: 🖥️ BackEnd, 💾 Database, 💡 Feature, 💬 Gpt Review

#42 회원 TABLE 암호화, 회원 복호화 VIEW 추가.
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/db/migration/V1.0.5__insert_common_code_age_and_gender_and_create_table_auth.sql
  module-api/src/main/resources/db/migration/V1.0.6__modify_member_encrypt_and_create_decrypt_member_view.sql
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
Labels: 🖥️ BackEnd, 💾 Database

#44 샘플 Product 데이터 50개 가량 추가
  module-api/src/main/resources/db/migration/V1.0.7__insert_sample_data_to_product_and_brand.sql
Labels: 💾 Database, ⚙️ Settings

#45 feature :: 회원가입시 아이디, 이메일 중복검사 확인
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#51 fixed :: 컨트롤러 맵핑 ModelAttribute -> RequestBody 변경
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#56 [feat] 공통 에러 처리 및 API 응답 관련 추가
  module-api/src/main/java/com/kernel360/commoncode/code/CommonCodeBusinessCode.java
  module-api/src/main/java/com/kernel360/commoncode/code/CommonCodeErrorCode.java
  module-common/build.gradle
  module-common/src/main/java/com/kernel360/code/BaseCode.java
  module-common/src/main/java/com/kernel360/code/BusinessCode.java
  module-common/src/main/java/com/kernel360/code/ErrorCode.java
  module-common/src/main/java/com/kernel360/code/common/CommonBusinessCode.java
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/exception/BusinessException.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
  module-common/src/main/java/com/kernel360/response/ApiResponse.java
  module-common/src/main/java/com/kernel360/response/ErrorResponse.java
Labels: 🖥️ BackEnd, 💡 Feature

#57 Feature/product testcode
  docker-compose.yml
  module-api/build.gradle
  module-api/lombok.config
  module-api/src/main/java/com/kernel360/commoncode/dto/CommonCodeDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/entity/MemberTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/dto/ProductDtoTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/auth/entity/Auth.java
  module-domain/src/main/java/com/kernel360/auth/repository/AuthRepository.java
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/commoncode/entity/CommonCode.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
Labels: 💡 Feature

#62 feature :: 특정 API 접근 검증, 토큰 검증 및 재발급 기능
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/global/code/AcceptInterceptorErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-common/src/main/java/com/kernel360/utils/JWT.java
  module-domain/src/main/java/com/kernel360/auth/repository/AuthRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#61 [feat] 테이블 내 xxx_no 컬럼 타입 일괄 변경 (8바이트 정수)
  module-api/src/main/resources/db/migration/V1.0.8__modify_member_no_column_type.sql
  module-api/src/main/resources/db/migration/V1.0.9__modify_no_column_type_in_tables.sql
Labels: 🖥️ BackEnd, 💾 Database

#63 브랜드 목록에서 각 브랜드의 제품을 읽어오는 배치 작업 추가
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/resources/db/migration/V1.1.0__alter_reported_product_column_type.sql
  module-api/src/main/resources/db/migration/V1.1.1__alter_brand_and_product_table.sql
  module-batch/src/main/java/com/kernel360/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/dto/ProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/ImportProductFromReportedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/JpaProductListWriter.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/client/ApiClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/client/ReportedProductClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/client/ReportedProductDetailClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/client/ReportedProductFromBrandClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDetailDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDetailListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/FetchReportedProductListFromBrandItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductDetailApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductDetailItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductListItemReader.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductListItemWriter.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/service/ReportedProductService.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ReportedProductScheduler.java
  module-batch/src/test/java/com/kernel360/modulebatch/client/ReportedProductClientTest.java
  module-batch/src/test/java/com/kernel360/modulebatch/job/ReportedProductApiJobConfigTest.java
  module-batch/src/test/java/com/kernel360/modulebatch/service/ReportedProductServiceTest.java
  module-domain/src/main/java/com/kernel360/brand/entity/Brand.java
  module-domain/src/main/java/com/kernel360/brand/repository/BrandRepository.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProductDetails.java
  module-domain/src/main/java/com/kernel360/ecolife/repository/ReportedProductRepository.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 💾 Database, 💡 Feature

#73 [feat] Rest Docs 적용
  .gitignore
  module-api/build.gradle
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/docs/asciidoc/overview.adoc
  module-api/src/docs/asciidoc/sample-api.adoc
  module-api/src/main/java/com/kernel360/commoncode/controller/CommonCodeController.java
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/common/utils/RestDocumentUtils.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerRestDocsTest.java
  module-api/src/test/resources/org/springframework/restdocs/templates/path-parameters.snippet
  module-api/src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  module-api/src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  module-api/src/test/resources/org/springframework/restdocs/templates/response-fields.snippet
Labels: 🖥️ BackEnd, 💡 Feature, ⚙️ Settings

#78 Feature :: 회원가입, 로그인 리팩터링 (#68, #77)
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/enumset/Age.java
  module-api/src/main/java/com/kernel360/member/enumset/Gender.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/entity/MemberTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#76 refactor : product 관련 설정 변경
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/resources/db/migration/V1.1.1__alter_brand_and_product_table.sql
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/product/entity/SafetyStatus.java
  module-domain/src/main/java/com/kernel360/product/entity/SafetyStatusConverter.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 💾 Database, 🔨 Refactor

#80 chose :: 회원 테이블 컬럼 명칭 및 자료형 변경
  module-api/src/main/resources/db/migration/V1.1.2__alter_table_member_and_add_common_code.sql
Labels: 💾 Database

#81 chose :: flyway v1.1.2 sql 에러 수정
  module-api/src/main/resources/db/migration/V1.1.2__alter_table_member_and_add_common_code.sql
Labels: 💾 Database

#82 chore :: v1.1.2 누락 된 if exists 재추가
  module-api/src/main/resources/db/migration/V1.1.2__alter_table_member_and_add_common_code.sql
Labels: 💾 Database

#83 개발용 신고대상생활화학제품 추가 배치 작업
  module-api/src/main/resources/db/migration/V1.1.1__alter_brand_and_product_table.sql
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/dto/ProductDtoTest.java
  module-batch/build.gradle
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/FetchReportedProductWithBrandSchedule.java
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/ImportProductFromReportedProductSchedule.java
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/QuartzConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/dto/ProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/ImportProductFromReportedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDetailDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductDetailApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductDetailItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductListItemReader.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/service/ReportedProductService.java
  module-domain/src/main/java/com/kernel360/ecolife/repository/ReportedProductRepository.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
Labels: 🖥️ BackEnd, 💾 Database

#85 [test] ControllerTest 변경 (MockBean 추가)
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#86 feature :: 생활화학 제품 데이터 추가 기능 갱신
  module-api/src/main/resources/db/migration/V1.1.1__alter_brand_and_product_table.sql
  module-batch/src/main/java/com/kernel360/modulebatch/product/dto/ProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/ImportProductFromReportedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/FetchReportedProductListFromBrandItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductDetailApiJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/ReportedProductFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/service/ReportedProductService.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ReportedProductScheduler.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProductDetails.java
  module-domain/src/main/java/com/kernel360/ecolife/repository/ReportedProductRepository.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 💾 Database, 🔨 Refactor

#89 Feature :: 위해우려제품 목록 정보를 초록누리에서 읽어와서 저장하기
  module-api/src/main/resources/db/migration/V1.1.3__create_concerned_product_table.sql
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/client/ConcernedProductListClient.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/dto/ConcernedProductDetailDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/dto/ConcernedProductDetailListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/dto/ConcernedProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/dto/ConcernedProductListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/job/core/FetchConcernedProductListFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/job/infra/ConcernedProductListItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/job/infra/ConcernedProductListItemWriter.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/service/ConcernedProductService.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDetailDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/dto/ReportedProductDetailListDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ConcernedProductScheduler.java
  module-batch/src/main/resources/application-local.yml
  module-domain/src/main/java/com/kernel360/ecolife/entity/ConcernedProduct.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ConcernedProductDetail.java
  module-domain/src/main/java/com/kernel360/ecolife/entity/ReportedProduct.java
  module-domain/src/main/java/com/kernel360/ecolife/repository/ConcernedProductRepository.java
Labels: 🖥️ BackEnd, 💾 Database

#91 chore :: docker-compose를 쓰지 않고 수동배포
  .github/workflows/gradle.yml
  module-api/src/main/resources/db/migration/V1.1.2__alter_table_member_and_add_common_code.sql
Labels: 🖥️ BackEnd

#92 [fix] log level 수정 & 리턴값 오류 수정
  module-api/src/main/java/com/kernel360/commoncode/controller/CommonCodeController.java
  module-api/src/main/resources/logback-spring.xml
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed, ⚙️ Settings

#93 chore :: 오타수정
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
Labels: chore

#95 [fix] 테스트에서 발생하는 오류 수정
  module-api/src/main/resources/db/migration/V1.1.2__alter_table_member_and_add_common_code.sql
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/mypage/controller/MyPageControllerTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#103 refactore/test code
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/docs/asciidoc/product-api.adoc
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/member/repository/DeletedMemberRepository.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#114 [refactor] Flyway SQL List 정리
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
  module-api/src/main/resources/db/migration/V1.0.1__alter_seq_increment.sql
  module-api/src/main/resources/db/migration/V1.0.1__init_batch_tables.sql
  module-api/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-api/src/main/resources/db/migration/V1.0.2__insert_common_code_initial_data.sql
  module-api/src/main/resources/db/migration/V1.0.3__initialize_batch_job_schema.sql
  module-api/src/main/resources/db/migration/V1.0.3__insert_initial_data.sql
  module-api/src/main/resources/db/migration/V1.0.4__create_reported_product_table.sql
  module-api/src/main/resources/db/migration/V1.0.5__insert_common_code_age_and_gender_and_create_table_auth.sql
  module-api/src/main/resources/db/migration/V1.0.6__modify_member_encrypt_and_create_decrypt_member_view.sql
  module-api/src/main/resources/db/migration/V1.0.7__insert_sample_data_to_product_and_brand.sql
  module-api/src/main/resources/db/migration/V1.0.8__modify_member_no_column_type.sql
  module-api/src/main/resources/db/migration/V1.0.9__modify_no_column_type_in_tables.sql
  module-api/src/main/resources/db/migration/V1.1.0__alter_reported_product_column_type.sql
  module-api/src/main/resources/db/migration/V1.1.1__alter_brand_and_product_table.sql
  module-api/src/main/resources/db/migration/V1.1.3__create_concerned_product_table.sql
Labels: 🖥️ BackEnd, 💾 Database, 🔨 Refactor

#112 [fix] WebConfig - resource handle 내용 추가
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#109 [chore] Deploy in Vultr
  .github/workflows/cicd-dev.yml
  .github/workflows/gradle.yml
  docker-compose.yml
  module-api/Dockerfile
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/logback-spring.xml
  module-batch/Dockerfile
  module-batch/gradle/wrapper/gradle-wrapper.jar
  module-batch/gradle/wrapper/gradle-wrapper.properties
  module-batch/src/main/resources/application-dev.yml
  module-batch/src/main/resources/logback-spring.xml
Labels: 🖥️ BackEnd, ⚙️ Settings, chore

#118 [feat] sql 일부 수정 (2)
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
Labels: 🖥️ BackEnd, 💾 Database
