Repository Kernel360/F1-WashFit-BE, pull requests merged in 2024-03, with the labels that each got.

#235 Fix : 패스워드 재설정 로직을 변경합니다
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberCredentialDto.java
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
Labels: 🖥️ BackEnd

#236 fix :: 내 세차 정보 조회 시, 선택할 수 있는 세차정보 옵션을 함께 반환하도록 변경
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
Labels: 🖥️ BackEnd, chore, 💉Hotfix

#239 hotfix :: 추천제품 20개 발송
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/main/dto/RecommendProductsDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 💾 Database

#241 hotfix :: product repository 코드 merge시 누락 된 메서드 추가
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 💉Hotfix

#243 hotfix :: 프론트엔드 버셀서버명 변경
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 💉Hotfix

#225 Feature : Admin 모듈 Brand CRUD 기능 추가
  module-admin/src/main/java/com/kernel360/brand/code/BrandBusinessCode.java
  module-admin/src/main/java/com/kernel360/brand/code/BrandErrorCode.java
  module-admin/src/main/java/com/kernel360/brand/controller/BrandController.java
  module-admin/src/main/java/com/kernel360/brand/dto/BrandDto.java
  module-admin/src/main/java/com/kernel360/brand/service/BrandService.java
  module-admin/src/main/java/com/kernel360/brand/service/BrandServiceImpl.java
  module-admin/src/main/java/com/kernel360/config/AdminAuditConfig.java
  module-domain/src/main/java/com/kernel360/brand/entity/Brand.java
  module-domain/src/main/java/com/kernel360/brand/repository/BrandRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#245 [feat] Querydsl 세팅 및 적용
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewSearchDto.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepository.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryDsl.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryImpl.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
  module-domain/build.gradle
  module-domain/src/main/java/com/kernel360/config/QuerydslConfig.java
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepository.java
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepositoryJpa.java
Labels: 🖥️ BackEnd, 💡 Feature, ⚙️ Settings

#246 hotfix :: 프론트엔드 버셀서버명 / 제거
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 💉Hotfix

#249 메인 브랜치로 merge 24.03.04
  .github/workflows/cicd-dev.yml
  module-admin/src/main/java/com/kernel360/brand/code/BrandBusinessCode.java
  module-admin/src/main/java/com/kernel360/brand/code/BrandErrorCode.java
  module-admin/src/main/java/com/kernel360/brand/controller/BrandController.java
  module-admin/src/main/java/com/kernel360/brand/dto/BrandDto.java
  module-admin/src/main/java/com/kernel360/brand/service/BrandService.java
  module-admin/src/main/java/com/kernel360/brand/service/BrandServiceImpl.java
  module-admin/src/main/java/com/kernel360/config/AdminAuditConfig.java
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
  module-api/src/main/java/com/kernel360/likes/service/LikeService.java
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/main/dto/RecommendProductsDto.java
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/MemberCredentialDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberInfo.java
  module-api/src/main/java/com/kernel360/member/enumset/AccountType.java
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewSearchDto.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepository.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryDsl.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryImpl.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
  module-api/src/main/resources/db/migration/V1.0.10__add_unique_constraint_review.sql
  module-api/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-api/src/main/resources/db/migration/V1.0.9__add_clientIP_to_auth.sql
  module-api/src/test/java/com/kernel360/main/controller/MainControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/entity/MemberTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/code/jwt/JwtErrorCode.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
  module-common/src/main/java/com/kernel360/utils/JWT.java
  module-domain/build.gradle
  module-domain/src/main/java/com/kernel360/brand/entity/Brand.java
  module-domain/src/main/java/com/kernel360/brand/repository/BrandRepository.java
  module-domain/src/main/java/com/kernel360/config/QuerydslConfig.java
  module-domain/src/main/java/com/kernel360/likes/entity/Like.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/member/entity/WithdrawMember.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepositoryJpa.java
Labels: ⚙️ Settings

#251 hotfix :: 헤더 자격증명요청 관련 코드 삭제
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 💉Hotfix

#254 hotfix :: washfit.vercel.app 삭제
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 💉Hotfix

#255 [hotfix] interceptor 내용 추가 (OPTIONS 메서드 관련)
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed, 💉Hotfix

#248 Fix : 비밀번호 재설정 링크가 FE 화면을 바라보도록 변경
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, chore, 💉Hotfix

#256 마이페이지 조회시 나이 조회 정상수행 처리 (enum) 수정
  module-api/src/main/java/com/kernel360/member/enumset/Age.java
Labels: 💉Hotfix

#258 Hotfix : GitHub secrets와 바인딩 되어 있지 않던 문제 해결
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
Labels: 🖥️ BackEnd, 💉Hotfix

#261 hotfix :: 마이페이지 연령대, 성별 수정
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
Labels: 🖥️ BackEnd, 💉Hotfix

#262 fix :: 비밀번호 변경시 기존의 비밀번호를 입력하지 못하도록 유효성 검사하는 조건이 반대로 걸려있던 조건문 수정
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
Labels: 💉Hotfix

#260 Feature::즐겨찾기,메인페이지검색 api 추가
  module-admin/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/main/java/com/kernel360/likes/controller/LikeController.java
  module-api/src/main/java/com/kernel360/likes/dto/LikeSearchDto.java
  module-api/src/main/java/com/kernel360/likes/repository/LikeRepository.java
  module-api/src/main/java/com/kernel360/likes/repository/LikeRepositoryDsl.java
  module-api/src/main/java/com/kernel360/likes/repository/LikeRepositoryImpl.java
  module-api/src/main/java/com/kernel360/likes/service/LikeService.java
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/main/controller/Sort.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/dto/ProductResponse.java
  module-api/src/main/java/com/kernel360/product/dto/ProductSearchDto.java
  module-api/src/main/java/com/kernel360/product/repository/ProductRepository.java
  module-api/src/main/java/com/kernel360/product/repository/ProductRepositoryDsl.java
  module-api/src/main/java/com/kernel360/product/repository/ProductRepositoryImpl.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/ConcernedProductToProductListItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/ReportedProductToProductItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/UpdateProductFromViolatedProductItemProcessor.java
  module-domain/src/main/java/com/kernel360/likes/repository/LikeRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepositoryJpa.java
Labels: 🖥️ BackEnd, 💡 Feature

#264 Hotfix : 마이페이지 비밀번호 변경, 비밀번호 재설정 로직 수정
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
Labels: 🖥️ BackEnd, 💉Hotfix

#267 fix :: 통합검색시 조회조건 변경
  module-api/src/main/java/com/kernel360/product/repository/ProductRepositoryImpl.java
Labels: 🖥️ BackEnd, 💾 Database

#272 Feature : 관리자 페이지 - 리뷰 조회, 삭제 기능을 추가합니다
  module-admin/build.gradle
  module-admin/src/main/java/com/kernel360/review/code/ReviewBusinessCode.java
  module-admin/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-admin/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-admin/src/main/java/com/kernel360/review/dto/AdminReviewDto.java
  module-admin/src/main/java/com/kernel360/review/dto/ReviewSearchDto.java
  module-admin/src/main/java/com/kernel360/review/respository/ReviewRepository.java
  module-admin/src/main/java/com/kernel360/review/respository/ReviewRepositoryDsl.java
  module-admin/src/main/java/com/kernel360/review/respository/ReviewRepositoryImpl.java
  module-admin/src/main/java/com/kernel360/review/service/ReviewService.java
  module-admin/src/main/java/com/kernel360/review/service/ReviewServiceImpl.java
Labels: 🖥️ BackEnd

#273 hotfix:: bean 중복에러 수정
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#276 refactor:: yunNote 반영 리팩토링
  module-admin/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-admin/src/main/java/com/kernel360/product/service/ProductService.java
  module-admin/src/main/resources/application-local.yml
  module-admin/src/main/resources/application.yml
  module-api/src/main/java/com/kernel360/likes/controller/LikeController.java
  module-api/src/main/java/com/kernel360/likes/dto/LikeSearchDto.java
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/main/conveter/StringToSortConverter.java
  module-api/src/main/java/com/kernel360/main/enumset/Sort.java
  module-api/src/main/java/com/kernel360/member/dto/PasswordDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductSearchDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/com/kernel360/main/controller/MainControllerTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/dto/ProductDto.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/ConcernedProductToProductListItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/ReportedProductToProductItemProcessor.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/product/entity/SafetyStatusConverter.java
  module-domain/src/main/java/com/kernel360/product/enumset/SafetyStatus.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#279 Fix :: CommonCode, WashInfo 에서 테이블과 데이터 타입이 맞지 않는 필드 수정
  module-api/src/main/java/com/kernel360/commoncode/dto/CommonCodeDto.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerRestDocsTest.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-batch/build.gradle
  module-batch/src/main/java/com/kernel360/modulebatch/ModuleBatchApplication.java
  module-domain/src/main/java/com/kernel360/commoncode/entity/CommonCode.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
Labels: 🖥️ BackEnd, chore

#282 fix :: 카카오 요청 헤더 속성값 변경
  module-api/src/main/java/com/kernel360/member/service/KakaoRequest.java
Labels: chore

#283 [feat] 리뷰 + 파일 기능 추가 및 리팩토링
  module-admin/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-admin/src/main/resources/application.yml
  module-api/src/main/java/com/kernel360/file/repository/FileRepository.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewRequestDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewResponseDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewSearchDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewSearchResult.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepository.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryDsl.java
  module-api/src/main/java/com/kernel360/review/repository/ReviewRepositoryImpl.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/db/migration/V1.0.11__create_file_table.sql
  module-api/src/main/resources/db/migration/V1.0.12__modify_review_table.sql
  module-common/src/main/java/com/kernel360/utils/file/FileUtils.java
  module-common/src/main/java/com/kernel360/utils/file/S3BucketPath.java
  module-domain/src/main/java/com/kernel360/file/entity/File.java
  module-domain/src/main/java/com/kernel360/file/entity/FileReferType.java
  module-domain/src/main/java/com/kernel360/file/repository/FileRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/review/entity/Review.java
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepositoryJpa.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#286 [feat] 리뷰 API 수정 (이전 PR 내 이슈 수정)
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-domain/src/main/java/com/kernel360/file/entity/File.java
  module-domain/src/main/java/com/kernel360/file/repository/FileRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/review/entity/Review.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#288 Fix : Jenkins 를 통해 Spring Batch Job 을 실행시킬 수 있도록 코드 수정
  .github/workflows/cicd-dev.yml
  module-batch/src/main/java/com/kernel360/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/FetchReportedProductWithBrandSchedule.java
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/ImportProductFromReportedProductSchedule.java
  module-batch/src/main/java/com/kernel360/modulebatch/Quartz/QuartzConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/job/core/FetchConcernedProductDetailJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/concernedproduct/job/core/FetchConcernedProductListFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/global/BaseJobExecutionListener.java
  module-batch/src/main/java/com/kernel360/modulebatch/global/BaseStepExecutionListener.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/core/ImportProductFromConcernedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/core/ImportProductFromReportedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/core/UpdateProductFromViolatedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/ConcernedProductToProductListItemProcessor.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/core/FetchReportedProductDetailJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/core/FetchReportedProductListJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/core/ReportedProductFromBrandJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/reportedproduct/job/infra/ReportedProductListItemWriter.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ConcernedProductScheduler.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ReportedProductScheduler.java
  module-batch/src/main/java/com/kernel360/modulebatch/scheduler/ViolatedProductScheduler.java
  module-batch/src/main/java/com/kernel360/modulebatch/violatedproduct/job/core/FetchViolatedProductDetailJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/violatedproduct/job/core/FetchViolatedProductListJobConfig.java
  module-batch/src/main/resources/application-dev.yml
  module-batch/src/main/resources/application.yml
Labels: 🖥️ BackEnd, 🔨 Refactor

#289 Fix : createdAt, modifiedAt의 타입을 LocalDateTime 으로 변경
  module-admin/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-admin/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-admin/src/main/java/com/kernel360/review/dto/AdminReviewDto.java
  module-admin/src/main/java/com/kernel360/review/service/ReviewServiceImpl.java
  module-admin/src/test/java/com/kernel360/ModuleAdminApplicationTests.java
  module-api/src/main/java/com/kernel360/commoncode/dto/CommonCodeDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewRequestDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewResponseDto.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewSearchResult.java
  module-api/src/main/resources/db/migration/V1.0.13__modify_datetime_type.sql
  module-api/src/main/resources/db/migration/V1.0.14__recreate_member_view.sql
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerRestDocsTest.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/base/BaseRawEntity.java
Labels: 🖥️ BackEnd, 💾 Database, ⚙️ Settings

#290 feature 게시판 API 초안 작성
  module-api/src/main/java/com/kernel360/bbs/code/BBSBusinessCode.java
  module-api/src/main/java/com/kernel360/bbs/code/BBSErrorCode.java
  module-api/src/main/java/com/kernel360/bbs/controller/BBSController.java
  module-api/src/main/java/com/kernel360/bbs/dto/BBSDto.java
  module-api/src/main/java/com/kernel360/bbs/dto/BBSListDto.java
  module-api/src/main/java/com/kernel360/bbs/enumset/BBSType.java
  module-api/src/main/java/com/kernel360/bbs/repository/BBSRepository.java
  module-api/src/main/java/com/kernel360/bbs/repository/BBSRepositoryDSL.java
  module-api/src/main/java/com/kernel360/bbs/repository/BBSRepositoryDSLImpl.java
  module-api/src/main/java/com/kernel360/bbs/service/BBSService.java
  module-api/src/main/java/com/kernel360/global/config/AuditConfig.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/resources/db/migration/V1.0.15__create_BBS.sql
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-domain/src/main/java/com/kernel360/bbs/entity/BBS.java
  module-domain/src/main/java/com/kernel360/bbs/repository/BBSRepositoryJPA.java
Labels: 🖥️ BackEnd, 💡 Feature

#293 fix :: 로그 출력시 Trie를 이용한 denined 목록 추가
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/global/filter/LogFilter.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
Labels: 🖥️ BackEnd, ⚙️ Settings, 💉Hotfix

#295 hotfix :: 액추에이터 response 로그만 나오지 않도록 수정
  module-api/src/main/java/com/kernel360/global/filter/LogFilter.java
Labels: chore, 💉Hotfix

#296 [hotfix] cicd yml modify
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, 💉Hotfix

#297 [hotfix] cicd yml modify (재반영)
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#291 Feature:: Admin 회원관리 api 추가
  module-admin/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-admin/src/main/java/com/kernel360/member/controller/MemberController.java
  module-admin/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-admin/src/main/java/com/kernel360/member/dto/MemberResponse.java
  module-admin/src/main/java/com/kernel360/member/dto/MemberSearchDto.java
  module-admin/src/main/java/com/kernel360/member/enumset/Age.java
  module-admin/src/main/java/com/kernel360/member/enumset/Gender.java
  module-admin/src/main/java/com/kernel360/member/enumset/Sort.java
  module-admin/src/main/java/com/kernel360/member/repository/MemberRepository.java
  module-admin/src/main/java/com/kernel360/member/repository/MemberRepositoryDsl.java
  module-admin/src/main/java/com/kernel360/member/repository/MemberRepositoryImpl.java
  module-admin/src/main/java/com/kernel360/member/service/MemberService.java
  module-admin/src/main/java/com/kernel360/review/repository/ReviewRepository.java
  module-admin/src/main/java/com/kernel360/review/repository/ReviewRepositoryDsl.java
  module-admin/src/main/java/com/kernel360/review/repository/ReviewRepositoryImpl.java
  module-admin/src/main/java/com/kernel360/review/respository/ReviewRepository.java
  module-admin/src/main/java/com/kernel360/review/service/ReviewServiceImpl.java
  module-api/src/main/java/com/kernel360/member/service/KakaoRequest.java
  module-domain/src/main/java/com/kernel360/admin/entity/Admin.java
  module-domain/src/main/java/com/kernel360/admin/repository/AdminRepository.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/product/converter/SafetyStatusConverter.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
Labels: 🖥️ BackEnd, 💡 Feature

#298 hotfix:: ci/cd error 수정
  module-api/src/main/java/com/kernel360/member/repository/MemberRepository.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#294 Feature:: 비속어 필터링 기능 추가
  module-admin/src/main/java/com/kernel360/review/service/ReviewServiceImpl.java
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/global/annotation/BadWordFilter.java
  module-api/src/main/java/com/kernel360/global/badwordfilter/BadWordValidator.java
  module-api/src/main/java/com/kernel360/member/repository/MemberRepository.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewRequestDto.java
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
  module-domain/src/main/java/com/kernel360/member/repository/AdminRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#301 [feat] 세차장 리뷰 기능 + 리뷰 기능 보완
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-api/src/main/java/com/kernel360/washzone/dto/WashZoneDto.java
  module-api/src/main/java/com/kernel360/washzonereview/code/WashzoneReviewBusinessCode.java
  module-api/src/main/java/com/kernel360/washzonereview/code/WashzoneReviewErrorCode.java
  module-api/src/main/java/com/kernel360/washzonereview/controller/WashzoneReviewController.java
  module-api/src/main/java/com/kernel360/washzonereview/dto/WashzoneReviewRequestDto.java
  module-api/src/main/java/com/kernel360/washzonereview/dto/WashzoneReviewResponseDto.java
  module-api/src/main/java/com/kernel360/washzonereview/dto/WashzoneReviewSearchDto.java
  module-api/src/main/java/com/kernel360/washzonereview/dto/WashzoneReviewSearchResult.java
  module-api/src/main/java/com/kernel360/washzonereview/repository/WashzoneReviewRepository.java
  module-api/src/main/java/com/kernel360/washzonereview/repository/WashzoneReviewRepositoryDsl.java
  module-api/src/main/java/com/kernel360/washzonereview/repository/WashzoneReviewRepositoryImpl.java
  module-api/src/main/java/com/kernel360/washzonereview/service/WashzoneReviewService.java
  module-api/src/main/resources/db/migration/V1.0.16__create_washzone_review_table.sql
  module-domain/src/main/java/com/kernel360/file/entity/FileReferType.java
  module-domain/src/main/java/com/kernel360/member/repository/AdminRepository.java
  module-domain/src/main/java/com/kernel360/member/repository/MemberRepositoryJpa.java
  module-domain/src/main/java/com/kernel360/washzone/entity/WashZone.java
  module-domain/src/main/java/com/kernel360/washzonereview/entity/WashzoneReview.java
  module-domain/src/main/java/com/kernel360/washzonereview/repository/WashzoneReviewRepositoryJpa.java
Labels: 🖥️ BackEnd, 💡 Feature

#304 [fix] 제품/세차장 리뷰 도메인에 비속어 필터링 적용 및 글로벌 Exception 수정
  module-api/src/main/java/com/kernel360/review/dto/ReviewRequestDto.java
  module-api/src/main/java/com/kernel360/washzonereview/controller/WashzoneReviewController.java
  module-api/src/main/java/com/kernel360/washzonereview/dto/WashzoneReviewRequestDto.java
  module-common/build.gradle
  module-common/src/main/java/com/kernel360/code/common/CommonErrorCode.java
  module-common/src/main/java/com/kernel360/code/common/ValidationMessage.java
  module-common/src/main/java/com/kernel360/handler/GlobalExceptionHandler.java
  module-common/src/main/java/com/kernel360/response/ErrorResponse.java
Labels: 🐞 Bug, 🖥️ BackEnd, 🔨 Refactor

#305 [feat] log aop 내용 추가
  module-api/src/main/java/com/kernel360/global/aop/LogAspect.java
Labels: 🖥️ BackEnd, 💡 Feature

#309 [refactor] sql 위치 변경 및 ecr 이미지 사용 관련
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  module-batch/src/main/resources/application-prod.yml
  module-domain/src/main/resources/db/migration/V1.0.0__init.sql
  module-domain/src/main/resources/db/migration/V1.0.10__add_unique_constraint_review.sql
  module-domain/src/main/resources/db/migration/V1.0.11__create_file_table.sql
  module-domain/src/main/resources/db/migration/V1.0.12__modify_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.13__modify_datetime_type.sql
  module-domain/src/main/resources/db/migration/V1.0.14__recreate_member_view.sql
  module-domain/src/main/resources/db/migration/V1.0.15__create_BBS.sql
  module-domain/src/main/resources/db/migration/V1.0.16__create_washzone_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.1__init_batch_tables.sql
  module-domain/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-domain/src/main/resources/db/migration/V1.0.3__insert_initial_data.sql
  module-domain/src/main/resources/db/migration/V1.0.4__init_washzone_table.sql
  module-domain/src/main/resources/db/migration/V1.0.5__create_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.6__init_likes.sql
  module-domain/src/main/resources/db/migration/V1.0.7__create_admin_table.sql
  module-domain/src/main/resources/db/migration/V1.0.8__insert_common_code_and_create_withraw_table.sql
  module-domain/src/main/resources/db/migration/V1.0.9__add_clientIP_to_auth.sql
Labels: 🖥️ BackEnd, 🔨 Refactor, ⚙️ Settings

#310 Main 브랜치 최신화 (24.03.18) (2)
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  module-batch/src/main/resources/application-prod.yml
  module-domain/src/main/resources/db/migration/V1.0.0__init.sql
  module-domain/src/main/resources/db/migration/V1.0.10__add_unique_constraint_review.sql
  module-domain/src/main/resources/db/migration/V1.0.11__create_file_table.sql
  module-domain/src/main/resources/db/migration/V1.0.12__modify_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.13__modify_datetime_type.sql
  module-domain/src/main/resources/db/migration/V1.0.14__recreate_member_view.sql
  module-domain/src/main/resources/db/migration/V1.0.15__create_BBS.sql
  module-domain/src/main/resources/db/migration/V1.0.16__create_washzone_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.1__init_batch_tables.sql
  module-domain/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-domain/src/main/resources/db/migration/V1.0.3__insert_initial_data.sql
  module-domain/src/main/resources/db/migration/V1.0.4__init_washzone_table.sql
  module-domain/src/main/resources/db/migration/V1.0.5__create_review_table.sql
  module-domain/src/main/resources/db/migration/V1.0.6__init_likes.sql
  module-domain/src/main/resources/db/migration/V1.0.7__create_admin_table.sql
  module-domain/src/main/resources/db/migration/V1.0.8__insert_common_code_and_create_withraw_table.sql
  module-domain/src/main/resources/db/migration/V1.0.9__add_clientIP_to_auth.sql
Labels: 🖥️ BackEnd

#312 [feat] REST Docs + Swagger UI
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/global/filter/LogFilter.java
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerRestDocsTest.java
  module-api/src/test/java/com/kernel360/review/controller/ReviewControllerTest.java
Labels: 🖥️ BackEnd, 💡 Feature, ⚙️ Settings

#314 Refactor:: api 성능개선,
  module-api/src/main/java/com/kernel360/ModuleApiApplication.java
  module-api/src/main/java/com/kernel360/global/aop/LogAspect.java
  module-api/src/main/java/com/kernel360/global/filter/LogFilter.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
Labels: 🖥️ BackEnd, 🔨 Refactor
