Repository Kernel360/F1-WashFit-BE, pull requests merged in 2024-02, with the labels that each got.

#121 [feat] sql 수정 (+ 초기화를 편하게 하기 위한 작업)
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
  module-api/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-api/src/main/resources/db/migration/V1.0.3__insert_initial_data.sql
Labels: 🖥️ BackEnd, 💾 Database

#122 feat:: 부가정보입력 controller추가, 테이블간 변수명 통일
  .gitignore
  module-api/src/docs/asciidoc/index.adoc
  module-api/src/main/java/com/kernel360/main/controller/MainContoller.java
  module-api/src/main/java/com/kernel360/main/dto/BannerDto.java
  module-api/src/main/java/com/kernel360/main/dto/RecommendProductsDto.java
  module-api/src/main/java/com/kernel360/main/service/MainService.java
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/CarInfoDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberInfo.java
  module-api/src/main/java/com/kernel360/member/dto/WashInfoDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/main/controller/MainContollerTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/dto/ProductDtoTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/brand/entity/Brand.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#132 [feat] cors 관련 config 추가
  module-api/src/main/java/com/kernel360/global/config/WebConfig.java
Labels: 🖥️ BackEnd, 💡 Feature

#134 feat::pagination 기능추가, 관련 테스트코드 수정
  module-api/src/main/java/com/kernel360/main/controller/MainContoller.java
  module-api/src/main/java/com/kernel360/main/controller/Sort.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/main/controller/MainContollerTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#135 chore :: 모니터링 시스템을 위한 스프링 액추에이터 설정 추가
  module-api/build.gradle
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
Labels: 🖥️ BackEnd, chore

#136 fix:: ProductServiceTest 에러코드 수정
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
Labels: 🐞 Bug, 🖥️ BackEnd

#137 [chore] setting 수정 및 불필요 내용 정리
  module-api/src/docs/asciidoc/overview.adoc
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application.yml
  module-api/src/main/resources/static/favicon.ico
  module-common/src/main/java/com/kernel360/utils/jasypt/EncryptionConfiguration.java
  module-common/src/main/java/com/kernel360/utils/jasypt/JasyptEncryptor.java
Labels: 🖥️ BackEnd, ⚙️ Settings, chore

#138 chore:: gpt-review 삭제
  .github/workflows/cr.yml
Labels: 🖥️ BackEnd, chore

#141 chore :: MYBATIS ORM 추가
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/commoncode/controller/CommonCodeController.java
  module-api/src/main/java/com/kernel360/commoncode/service/CommonCodeService.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-domain/build.gradle
  module-domain/src/main/java/com/kernel360/commoncode/mapper/CommonCodeMapper.java
  module-domain/src/main/java/com/kernel360/commoncode/vo/CommonCodeVO.java
  module-domain/src/main/java/com/kernel360/config/MybatisConfig.java
Labels: 🖥️ BackEnd, 💾 Database, chore

#149 feature :: 제품 상세정보 조회
  module-api/src/main/java/com/kernel360/main/controller/MainContoller.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/main/controller/MainContollerTest.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#147 [Hotfix] 사용하지 않는 제품을 product 테이블에서 삭제하는 작업 추가
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/core/ImportProductFromReportedProductJobConfig.java
  module-batch/src/main/java/com/kernel360/modulebatch/product/job/infra/FilterUnusedProductTasklet.java
Labels: 🖥️ BackEnd, 💾 Database

#157 Hotfix :: 제품 도메인 테스트코드 긴급 수정
  module-api/src/docs/asciidoc/product-api.adoc
  module-api/src/main/java/com/kernel360/product/dto/ProductDetailDto.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
Labels: 🖥️ BackEnd, 💉Hotfix

#143 feature :: KaKao Map 세차장정보 API
  module-api/src/docs/asciidoc/product-api.adoc
  module-api/src/main/java/com/kernel360/washzone/code/WashZoneBusinessCode.java
  module-api/src/main/java/com/kernel360/washzone/code/WashZoneErrorCode.java
  module-api/src/main/java/com/kernel360/washzone/controller/WashZoneController.java
  module-api/src/main/java/com/kernel360/washzone/dto/KakaoMapDto.java
  module-api/src/main/java/com/kernel360/washzone/dto/WashZoneDto.java
  module-api/src/main/java/com/kernel360/washzone/service/WashZoneService.java
  module-api/src/main/resources/db/migration/V1.0.4__init_washzone_table.sql
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-domain/src/main/java/com/kernel360/washzone/entity/WashZone.java
  module-domain/src/main/java/com/kernel360/washzone/repository/WashZoneRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#159 Hotfix :: 테스트용 공통코드 테스트 코드 수정
  module-api/src/test/java/com/kernel360/commoncode/controller/CommonCodeControllerRestDocsTest.java
Labels: 💉Hotfix

#162 Feature : 제품상세 조회시 조회수 카운트를 증가시키는 로직 구현
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd

#156 Feature : 가입시 입력한 이메일로 분실한 회원 아이디를 발송하는 기능
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  module-api/build.gradle
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/FindMemberIdFromEmailDto.java
  module-api/src/main/java/com/kernel360/member/service/EmailSender.java
  module-api/src/main/java/com/kernel360/member/service/FindService.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
Labels: 🖥️ BackEnd

#165 [feat] 리뷰 기본 기능 개발
  module-api/src/main/java/com/kernel360/product/dto/ProductDto.java
  module-api/src/main/java/com/kernel360/review/code/ReviewBusinessCode.java
  module-api/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/dto/ReviewDto.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-api/src/main/resources/db/migration/V1.0.5__create_review_table.sql
  module-domain/src/main/java/com/kernel360/base/BaseEntity.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
  module-domain/src/main/java/com/kernel360/review/entity/Review.java
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#167 Feature:: 좋아요 기능구현, 즐겨찾기목록조회 기능구현
  module-api/src/main/java/com/kernel360/likes/code/LikeBusinessCode.java
  module-api/src/main/java/com/kernel360/likes/code/LikeErrorCode.java
  module-api/src/main/java/com/kernel360/likes/controller/LikeController.java
  module-api/src/main/java/com/kernel360/likes/service/LikeService.java
  module-api/src/main/resources/db/migration/V1.0.5__init_likes.sql
  module-api/src/main/resources/db/migration/V1.0.6__init_likes.sql
  module-domain/src/main/java/com/kernel360/likes/entity/Like.java
  module-domain/src/main/java/com/kernel360/likes/repository/LikeRepository.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/product/entity/Product.java
Labels: 🖥️ BackEnd, 💡 Feature

#169 refactor :: 인증 관련 코드 리팩터링
  module-api/src/docs/asciidoc/auth-api.adoc
  module-api/src/main/java/com/kernel360/auth/code/AuthBusinessCode.java
  module-api/src/main/java/com/kernel360/auth/code/AuthErrorCode.java
  module-api/src/main/java/com/kernel360/auth/controller/AuthController.java
  module-api/src/main/java/com/kernel360/auth/dto/AuthDto.java
  module-api/src/main/java/com/kernel360/auth/service/AuthService.java
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/auth/controller/AuthControllerTest.java
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#171 hotfix:: sql 추가
  module-api/src/main/resources/db/migration/V1.0.5__init_likes.sql
Labels: 🐞 Bug, 🖥️ BackEnd

#173 refactor:: 제품리스트 요청 api 수정
  module-api/src/main/java/com/kernel360/main/controller/Sort.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-domain/src/main/java/com/kernel360/likes/repository/LikeRepository.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#180 Refactor/api
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#175 setting::module-admin 초기세팅
  module-admin/build.gradle
  module-admin/gradle/wrapper/gradle-wrapper.jar
  module-admin/gradle/wrapper/gradle-wrapper.properties
  module-admin/gradlew
  module-admin/gradlew.bat
  module-admin/src/main/java/com/kernel360/ModuleAdminApplication.java
  module-admin/src/main/resources/application-local.yml
  module-admin/src/main/resources/application.yml
  module-admin/src/main/resources/logback-spring.xml
  module-admin/src/test/java/com/kernel360/ModuleAdminApplicationTests.java
  settings.gradle
Labels: 🖥️ BackEnd, ⚙️ Settings

#178 Feature : 비밀번호 재설정 기능 추가
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  module-api/build.gradle
  module-api/src/docs/asciidoc/member-find-credential-api.adoc
  module-api/src/main/java/com/kernel360/global/config/RedisConfig.java
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/dto/FindMemberIdFromEmailDto.java
  module-api/src/main/java/com/kernel360/member/dto/MemberCredentialDto.java
  module-api/src/main/java/com/kernel360/member/service/EmailSender.java
  module-api/src/main/java/com/kernel360/member/service/FindCredentialService.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/member/service/RedisUtils.java
  module-api/src/main/java/com/kernel360/member/service/SendEmailService.java
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
Labels: 🖥️ BackEnd, 💡 Feature

#182 fix :: ci-cd.yml github.secrets 바인딩 누락 수정
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, 💉Hotfix

#183 fix :: 어플리케이션 레벨 비밀번호 암호화 누락 수정
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed, 💉Hotfix

#188 * 테스트코드 빌드 에러 수정
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
Labels: chore

#190 feat :: Exception 처리 추가
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/test/java/com/kernel360/common/ControllerTest.java
  module-api/src/test/java/com/kernel360/main/controller/MainControllerTest.java
Labels: 🖥️ BackEnd, 🛠️ Bug Fixed

#192 Refactor::api API 점검후 에러가 나는 api 수정, 테스트
  controllerTester.http
  http-client.env.json
  memberSetting.http
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/member/dto/MemberInfo.java
  module-api/src/main/java/com/kernel360/member/dto/PasswordDto.java
  module-api/src/main/java/com/kernel360/member/dto/WashInfoDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/java/com/kernel360/product/code/ProductsBusinessCode.java
  module-api/src/main/java/com/kernel360/product/code/ProductsErrorCode.java
  module-api/src/test/java/com/kernel360/mypage/controller/MyPageControllerTest.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#198 fix :: interceptor 추가로 인한 테스트 코드 수정
  module-api/src/main/java/com/kernel360/auth/controller/AuthController.java
  module-api/src/test/java/com/kernel360/auth/controller/AuthControllerTest.java
Labels: 🖥️ BackEnd, 💉Hotfix

#199 hotfix :: 디렉터리 변경에 따른 수정
  module-api/src/main/java/com/kernel360/likes/service/LikeService.java
  module-api/src/main/java/com/kernel360/main/controller/MainController.java
  module-api/src/main/java/com/kernel360/member/code/MemberErrorCode.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
Labels: 🖥️ BackEnd, 💉Hotfix

#201 feature :: 회원 탈퇴, 탈퇴 이력 추가
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-domain/src/main/java/com/kernel360/member/entity/WithrawMember.java
  module-domain/src/main/java/com/kernel360/member/repository/DeletedMemberRepository.java
  module-domain/src/main/java/com/kernel360/member/repository/WithrawMemberRepository.java
Labels: 🖥️ BackEnd

#203 DB :: 회원탈퇴 테이블 추가, 공통코드 레코드 수정 SQL
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/resources/db/migration/V1.0.8__insert_common_code_and_create_withraw_table.sql
  module-domain/src/main/java/com/kernel360/member/entity/WithdrawMember.java
  module-domain/src/main/java/com/kernel360/member/repository/WithdrawMemberRepository.java
Labels: 💾 Database

#205 Feature : 로그인 유저에 대한 IP validation 추가
  module-api/src/main/java/com/kernel360/auth/controller/AuthController.java
  module-api/src/main/java/com/kernel360/auth/service/AuthService.java
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/global/code/AcceptInterceptorErrorCode.java
  module-api/src/main/java/com/kernel360/member/controller/MemberController.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/resources/db/migration/V1.0.9__add_clientIP_to_auth.sql
  module-api/src/test/java/com/kernel360/auth/controller/AuthControllerTest.java
  module-api/src/test/java/com/kernel360/member/controller/MemberControllerTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-domain/src/main/java/com/kernel360/auth/entity/Auth.java
Labels: 🖥️ BackEnd, 💡 Feature

#209 hotfix :: typo_error_Member_Business_Code
  module-api/src/main/java/com/kernel360/member/code/MemberBusinessCode.java
Labels: chore, 💉Hotfix

#210 [setting] cicd-prod.yml 내용 추가
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, ⚙️ Settings, chore

#212 [merge] main 브랜치 반영 작업
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, ⚙️ Settings

#208 feat:: keyword + 정렬 api 추가
  module-api/src/main/java/com/kernel360/main/controller/Sort.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
Labels: 🖥️ BackEnd, 💡 Feature

#215 setting: cicd yml 일부 변경
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
Labels: 🖥️ BackEnd, 💉Hotfix

#218 hotfix:: ci/cd error 로 인한 testcode 주석처리
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
Labels: 🖥️ BackEnd, 💉Hotfix

#213 Fix :: 차량/세차 정보 조회 Json key 값을 변경합니다. 차량/세차 정보 저장 로직을 변경합니다.
  module-api/src/main/java/com/kernel360/global/config/RedisConfig.java
  module-api/src/main/java/com/kernel360/member/dto/CarInfoDto.java
  module-api/src/main/java/com/kernel360/member/dto/WashInfoDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/carinfo/repository/CarInfoRepository.java
  module-domain/src/main/java/com/kernel360/member/entity/WithrawMember.java
  module-domain/src/main/java/com/kernel360/member/repository/WithrawMemberRepository.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
  module-domain/src/main/java/com/kernel360/washinfo/repository/WashInfoRepository.java
Labels: 🖥️ BackEnd, 🔨 Refactor, 💉Hotfix

#216 [merge] main 브랜치 적용
  .github/workflows/cicd-dev.yml
  .github/workflows/cicd-prod.yml
  module-api/src/main/java/com/kernel360/global/config/RedisConfig.java
  module-api/src/main/java/com/kernel360/main/controller/Sort.java
  module-api/src/main/java/com/kernel360/member/dto/CarInfoDto.java
  module-api/src/main/java/com/kernel360/member/dto/WashInfoDto.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/java/com/kernel360/product/controller/ProductController.java
  module-api/src/main/java/com/kernel360/product/service/ProductService.java
  module-api/src/test/java/com/kernel360/product/controller/ProductControllerTest.java
  module-api/src/test/java/com/kernel360/product/service/ProductServiceTest.java
  module-domain/src/main/java/com/kernel360/carinfo/entity/CarInfo.java
  module-domain/src/main/java/com/kernel360/carinfo/repository/CarInfoRepository.java
  module-domain/src/main/java/com/kernel360/member/entity/WithrawMember.java
  module-domain/src/main/java/com/kernel360/member/repository/WithrawMemberRepository.java
  module-domain/src/main/java/com/kernel360/product/repository/ProductRepository.java
  module-domain/src/main/java/com/kernel360/washinfo/entity/WashInfo.java
  module-domain/src/main/java/com/kernel360/washinfo/repository/WashInfoRepository.java
Labels: 🖥️ BackEnd, chore

#222 refactor : .yml 파일에 jwt-expiring-time 지정하여 profile 별로 다르게 설정하여 사용하도록 수정
  module-api/src/main/resources/application-dev.yml
  module-api/src/main/resources/application-local.yml
  module-api/src/main/resources/application-prod.yml
  module-common/src/main/java/com/kernel360/utils/JWT.java
Labels: 🖥️ BackEnd, 💉Hotfix

#221 refactor:: 즐겨찾기 목록 요청 리팩토링
  module-api/src/main/java/com/kernel360/likes/service/LikeService.java
  module-domain/src/main/java/com/kernel360/likes/entity/Like.java
Labels: 🖥️ BackEnd, 🔨 Refactor

#227 Hotfix :: 세차 정보 예외 핸들링 추가
  module-api/src/main/java/com/kernel360/member/dto/MemberInfo.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
Labels: 🖥️ BackEnd, 💉Hotfix

#226 feature :: 회원가입, 로그인시 계정 타입 추가
  module-api/src/main/java/com/kernel360/member/dto/MemberDto.java
  module-api/src/main/java/com/kernel360/member/enumset/AccountType.java
  module-api/src/main/java/com/kernel360/member/service/MemberService.java
  module-api/src/main/java/com/kernel360/mypage/controller/MyPageController.java
  module-api/src/main/resources/db/migration/V1.0.0__init.sql
  module-api/src/main/resources/db/migration/V1.0.2__add_member_view_with_secure.sql
  module-api/src/test/java/com/kernel360/member/entity/MemberTest.java
  module-api/src/test/java/com/kernel360/member/service/MemberServiceTest.java
  module-domain/src/main/java/com/kernel360/member/entity/Member.java
  module-domain/src/main/java/com/kernel360/member/entity/WithdrawMember.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#229 [feat] 리뷰 API 보완 (페이징, 토큰 검증)
  module-api/src/main/java/com/kernel360/global/Interceptor/AcceptInterceptor.java
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
  module-api/src/main/java/com/kernel360/review/code/ReviewErrorCode.java
  module-api/src/main/java/com/kernel360/review/controller/ReviewController.java
  module-api/src/main/java/com/kernel360/review/service/ReviewService.java
  module-api/src/main/resources/db/migration/V1.0.10__add_unique_constraint_review.sql
  module-domain/src/main/java/com/kernel360/review/repository/ReviewRepository.java
Labels: 🖥️ BackEnd, 💡 Feature, 🔨 Refactor

#234 chore:: interceptor 경로추가
  module-api/src/main/java/com/kernel360/global/Interceptor/InterceptorConfig.java
Labels: 🖥️ BackEnd, chore
